import type { Category, MenuItem, RestaurantSettings } from "./types";

export const settings: RestaurantSettings = {
  name: "Sangwari",
  tagline: "Where every guest eats like family",
  welcome: "Jay Johar!",
  upiId: "shubz493@ybl",
  upiName: "Sangwari Restaurant",
  whatsappNumber: "917898217039",
  phoneDisplay: "+91 78982 17039",
  address: "Raipur Road, Mahasamund, Chhattisgarh 493445",
  mapUrl: "https://maps.app.goo.gl/FMRE6viCFePiujw58",
  hours: "11:00 AM – 11:00 PM",
  isOpen: true,
  deliveryFee: 30,
  minOrder: 99,
  taxPercent: 5,
  instagram: "sangwari",
};

export const categories: Category[] = [
  { id: "breakfast",      name: "Breakfast",            emoji: "🍳", sortOrder: 1,  isActive: true },
  { id: "soups",          name: "Soups",                emoji: "🥣", sortOrder: 2,  isActive: true },
  { id: "noodles",        name: "Noodles",              emoji: "🍜", sortOrder: 3,  isActive: true },
  { id: "chinese-veg",    name: "Chinese (Veg)",        emoji: "🥬", sortOrder: 4,  isActive: true },
  { id: "chinese-nonveg", name: "Chinese (Non-Veg)",    emoji: "🍗", sortOrder: 5,  isActive: true },
  { id: "continental",    name: "Continental",          emoji: "🍕", sortOrder: 6,  isActive: true },
  { id: "tandoor-veg",    name: "Tandoor (Veg)",        emoji: "🧆", sortOrder: 7,  isActive: true },
  { id: "tandoor-nonveg", name: "Tandoor (Non-Veg)",    emoji: "🍖", sortOrder: 8,  isActive: true },
  { id: "roti",           name: "Roti Special",         emoji: "🫓", sortOrder: 9,  isActive: true },
  { id: "main-veg",       name: "Main Course (Veg)",    emoji: "🍛", sortOrder: 10, isActive: true },
  { id: "main-nonveg",    name: "Main Course (Non-Veg)",emoji: "🍲", sortOrder: 11, isActive: true },
  { id: "biryani",        name: "Biryani Special",      emoji: "🍚", sortOrder: 12, isActive: true },
  { id: "mutton",         name: "Mutton Special",       emoji: "🥩", sortOrder: 13, isActive: true },
  { id: "fish",           name: "Fish Special",         emoji: "🐟", sortOrder: 14, isActive: true },
  { id: "beverages",      name: "Beverages & Shakes",   emoji: "🥤", sortOrder: 15, isActive: true },
  { id: "tea-coffee",     name: "Tea & Coffee",         emoji: "☕", sortOrder: 16, isActive: true },
  { id: "sweets-salads",  name: "Sweets & Salads",      emoji: "🍮", sortOrder: 17, isActive: true },
];

export const menuItems: MenuItem[] = [
  // ── BREAKFAST ──────────────────────────────────────────────────
  { id: "chhole-bhature",    categoryId: "breakfast", name: "Chhole Bhature (2 pc)", description: "Fluffy bhature served with spiced chickpea curry.",     price: 80,  emoji: "🫓", isVeg: true,  isAvailable: true, spiceLevel: 1, tags: ["bestseller"], sortOrder: 1 },
  { id: "aloo-paratha",      categoryId: "breakfast", name: "Aloo Paratha",          description: "Whole-wheat flatbread stuffed with spiced potato.",      price: 40,  emoji: "🫓", isVeg: true,  isAvailable: true, spiceLevel: 1, sortOrder: 2 },
  { id: "paneer-paratha",    categoryId: "breakfast", name: "Paneer Paratha",        description: "Flatbread stuffed with fresh cottage cheese filling.",    price: 50,  emoji: "🫓", isVeg: true,  isAvailable: true, spiceLevel: 1, sortOrder: 3 },
  { id: "gobhi-paratha",     categoryId: "breakfast", name: "Gobhi Paratha",         description: "Flatbread stuffed with spiced cauliflower.",              price: 40,  emoji: "🫓", isVeg: true,  isAvailable: true, spiceLevel: 1, sortOrder: 4 },
  { id: "paratha",           categoryId: "breakfast", name: "Paratha",               description: "Plain whole-wheat flatbread, served with pickle.",        price: 50,  emoji: "🫓", isVeg: true,  isAvailable: true, spiceLevel: 0, sortOrder: 5 },
  { id: "plain-dosa",        categoryId: "breakfast", name: "Plain Dosa",            description: "Crispy South-Indian rice crepe.",                         price: 30,  emoji: "🥞", isVeg: true,  isAvailable: true, spiceLevel: 0, sortOrder: 6 },
  { id: "masala-dosa",       categoryId: "breakfast", name: "Masala Dosa",           description: "Crispy dosa filled with spiced potato masala.",           price: 40,  emoji: "🥞", isVeg: true,  isAvailable: true, spiceLevel: 1, tags: ["bestseller"], sortOrder: 7 },
  { id: "cutting-dosa",      categoryId: "breakfast", name: "Cutting Dosa",          description: "Thick, soft dosa cut into pieces — easy to eat.",         price: 50,  emoji: "🥞", isVeg: true,  isAvailable: true, spiceLevel: 1, sortOrder: 8 },
  { id: "chana-poha",        categoryId: "breakfast", name: "Chana Poha",            description: "Light flattened rice tossed with chickpeas and spices.",   price: 20,  emoji: "🍽️", isVeg: true,  isAvailable: true, spiceLevel: 1, sortOrder: 9 },
  { id: "palak-puri",        categoryId: "breakfast", name: "Palak Puri",            description: "Deep-fried puffed bread made with spinach dough.",        price: 30,  emoji: "🍽️", isVeg: true,  isAvailable: true, spiceLevel: 1, sortOrder: 10 },
  { id: "methi-puri",        categoryId: "breakfast", name: "Methi Puri",            description: "Puffed bread flavoured with fenugreek leaves.",           price: 30,  emoji: "🍽️", isVeg: true,  isAvailable: true, spiceLevel: 1, sortOrder: 11 },

  // ── SOUPS (VEG) ──────────────────────────────────────────────
  { id: "manchow-soup",          categoryId: "soups", name: "Manchow Soup",           description: "Thick Indo-Chinese soup with vegetables and fried noodles.", price: 80,  emoji: "🥣", isVeg: true,  isAvailable: true, spiceLevel: 2, sortOrder: 1 },
  { id: "veg-hot-sour-soup",     categoryId: "soups", name: "Veg Hot & Sour Soup",    description: "Tangy and spicy clear vegetable soup.",                      price: 90,  emoji: "🥣", isVeg: true,  isAvailable: true, spiceLevel: 2, sortOrder: 2 },
  { id: "lemon-coriander-soup",  categoryId: "soups", name: "Lemon Coriander Soup",   description: "Fresh and light soup with lemon and coriander.",             price: 90,  emoji: "🥣", isVeg: true,  isAvailable: true, spiceLevel: 1, sortOrder: 3 },
  { id: "sweet-corn-soup",       categoryId: "soups", name: "Sweet Corn Soup",         description: "Creamy sweet corn soup with crunchy veggies.",              price: 90,  emoji: "🥣", isVeg: true,  isAvailable: true, spiceLevel: 0, sortOrder: 4 },
  { id: "tomato-soup",           categoryId: "soups", name: "Tomato Soup",             description: "Classic creamy tomato soup.",                               price: 80,  emoji: "🥣", isVeg: true,  isAvailable: true, spiceLevel: 0, sortOrder: 5 },
  { id: "cream-mushroom-soup",   categoryId: "soups", name: "Cream Mushroom Soup",     description: "Rich and creamy mushroom soup.",                            price: 110, emoji: "🥣", isVeg: true,  isAvailable: true, spiceLevel: 0, sortOrder: 6 },
  // SOUPS (NON-VEG)
  { id: "chicken-manchow-soup",      categoryId: "soups", name: "Chicken Manchow Soup",          description: "Thick Manchow soup with shredded chicken and crispy noodles.", price: 110, emoji: "🥣", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 7 },
  { id: "chicken-hot-sour-soup",     categoryId: "soups", name: "Chicken Hot & Sour Soup",       description: "Spicy and tangy soup with tender chicken pieces.",             price: 110, emoji: "🥣", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 8 },
  { id: "chicken-lemon-coriander",   categoryId: "soups", name: "Chicken Lemon Coriander Soup",  description: "Light and refreshing chicken soup with lemon.",                price: 120, emoji: "🥣", isVeg: false, isAvailable: true, spiceLevel: 1, sortOrder: 9 },

  // ── NOODLES ─────────────────────────────────────────────────
  { id: "chicken-chowmein",         categoryId: "noodles", name: "Chicken Chowmein",          description: "Stir-fried noodles with chicken and vegetables.",           price: 180, emoji: "🍜", isVeg: false, isAvailable: true, spiceLevel: 2, tags: ["bestseller"], sortOrder: 1 },
  { id: "chicken-hakka-noodles",    categoryId: "noodles", name: "Chicken Hakka Noodles",     description: "Classic Hakka-style noodles with chicken.",                 price: 180, emoji: "🍜", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 2 },
  { id: "chicken-schezwan-noodles", categoryId: "noodles", name: "Chicken Schezwan Noodles",  description: "Fiery Schezwan-sauce noodles with chicken.",                price: 180, emoji: "🍜", isVeg: false, isAvailable: true, spiceLevel: 3, sortOrder: 3 },
  { id: "egg-chowmein",             categoryId: "noodles", name: "Egg Chowmein",              description: "Stir-fried noodles with scrambled egg.",                    price: 140, emoji: "🍜", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 4 },
  { id: "egg-hakka-noodles",        categoryId: "noodles", name: "Egg Hakka Noodles",         description: "Hakka-style noodles tossed with egg.",                     price: 140, emoji: "🍜", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 5 },
  { id: "egg-schezwan-noodles",     categoryId: "noodles", name: "Egg Schezwan Noodles",      description: "Spicy Schezwan noodles with egg.",                         price: 140, emoji: "🍜", isVeg: false, isAvailable: true, spiceLevel: 3, sortOrder: 6 },

  // ── CHINESE (VEG) ───────────────────────────────────────────
  { id: "veg-noodles",          categoryId: "chinese-veg", name: "Veg Noodles",            description: "Stir-fried noodles with fresh vegetables.",                price: 80,  emoji: "🍜", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 1 },
  { id: "schezwan-noodles",     categoryId: "chinese-veg", name: "Schezwan Noodles",       description: "Spicy Schezwan-sauce noodles with vegetables.",             price: 90,  emoji: "🍜", isVeg: true, isAvailable: true, spiceLevel: 3, sortOrder: 2 },
  { id: "manchurian",           categoryId: "chinese-veg", name: "Manchurian",              description: "Crispy veg balls in a tangy Manchurian sauce.",             price: 110, emoji: "🥬", isVeg: true, isAvailable: true, spiceLevel: 2, tags: ["bestseller"], sortOrder: 3 },
  { id: "pasta-red",            categoryId: "chinese-veg", name: "Pasta Red",               description: "Penne pasta in a tangy red tomato sauce.",                  price: 120, emoji: "🍝", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 4 },
  { id: "pasta-white",          categoryId: "chinese-veg", name: "Pasta White",             description: "Creamy white sauce pasta.",                                 price: 130, emoji: "🍝", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 5 },
  { id: "schezwan-rice",        categoryId: "chinese-veg", name: "Schezwan Rice",           description: "Fiery Schezwan fried rice.",                               price: 90,  emoji: "🍚", isVeg: true, isAvailable: true, spiceLevel: 3, sortOrder: 6 },
  { id: "veg-fried-rice",       categoryId: "chinese-veg", name: "Veg Fried Rice",          description: "Wok-tossed fried rice with vegetables.",                   price: 130, emoji: "🍚", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 7 },
  { id: "veg-schezwan-rice",    categoryId: "chinese-veg", name: "Veg Schezwan Rice",       description: "Fried rice tossed in spicy Schezwan sauce.",               price: 150, emoji: "🍚", isVeg: true, isAvailable: true, spiceLevel: 3, sortOrder: 8 },
  { id: "french-fries",         categoryId: "chinese-veg", name: "French Fries",            description: "Crispy golden potato fries.",                              price: 90,  emoji: "🍟", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 9 },
  { id: "paneer-chilli",        categoryId: "chinese-veg", name: "Paneer Chilli",           description: "Crispy paneer tossed in chilli sauce.",                    price: 180, emoji: "🧀", isVeg: true, isAvailable: true, spiceLevel: 2, tags: ["bestseller"], sortOrder: 10 },
  { id: "paneer-65",            categoryId: "chinese-veg", name: "Paneer 65",               description: "Deep-fried spiced paneer, South-Indian style.",            price: 190, emoji: "🧀", isVeg: true, isAvailable: true, spiceLevel: 3, sortOrder: 11 },
  { id: "paneer-majestic",      categoryId: "chinese-veg", name: "Paneer Majestic",         description: "Crispy paneer in a rich majestic sauce.",                  price: 200, emoji: "🧀", isVeg: true, isAvailable: true, spiceLevel: 2, tags: ["chef-special"], sortOrder: 12 },
  { id: "paneer-dragon",        categoryId: "chinese-veg", name: "Paneer Dragon",           description: "Fiery dragon-sauce tossed crispy paneer.",                 price: 200, emoji: "🧀", isVeg: true, isAvailable: true, spiceLevel: 3, sortOrder: 13 },
  { id: "mushroom-chilli",      categoryId: "chinese-veg", name: "Mushroom Chilli",         description: "Sautéed mushrooms in spicy chilli sauce.",                 price: 170, emoji: "🍄", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 14 },
  { id: "mushroom-salt-pepper", categoryId: "chinese-veg", name: "Mushroom Salt & Pepper",  description: "Crispy mushrooms seasoned with salt and pepper.",          price: 180, emoji: "🍄", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 15 },
  { id: "baby-corn-chilli",     categoryId: "chinese-veg", name: "Baby Corn Chilli",        description: "Crispy baby corn tossed in chilli sauce.",                 price: 180, emoji: "🌽", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 16 },
  { id: "crispy-corn",          categoryId: "chinese-veg", name: "Crispy Corn",             description: "Golden crispy sweet corn kernels.",                       price: 160, emoji: "🌽", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 17 },
  { id: "lovely-corn",          categoryId: "chinese-veg", name: "Lovely Corn",             description: "Sweet corn tossed with butter and seasonings.",            price: 150, emoji: "🌽", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 18 },
  { id: "corn-salt-pepper",     categoryId: "chinese-veg", name: "Corn Salt & Pepper",      description: "Crunchy corn with salt and pepper.",                      price: 160, emoji: "🌽", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 19 },
  { id: "soya-chaap-65",        categoryId: "chinese-veg", name: "Soya Chaap 65",           description: "Crispy soya chaap, South-Indian 65 style.",               price: 200, emoji: "🍢", isVeg: true, isAvailable: true, spiceLevel: 3, sortOrder: 20 },
  { id: "chana-chilli",         categoryId: "chinese-veg", name: "Chana Chilli",            description: "Spiced chickpeas tossed in chilli sauce.",                price: 150, emoji: "🫘", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 21 },
  { id: "potato-honey-chilli",  categoryId: "chinese-veg", name: "Potato Honey Chilli",     description: "Crispy potato in a sweet-and-spicy honey chilli glaze.", price: 140, emoji: "🥔", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 22 },
  { id: "potato-chilli",        categoryId: "chinese-veg", name: "Potato Chilli",           description: "Crispy potato tossed in chilli sauce.",                  price: 120, emoji: "🥔", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 23 },
  { id: "veg-bullet",           categoryId: "chinese-veg", name: "Veg Bullet",              description: "Stuffed vegetable bullets — crispy outside, flavourful inside.", price: 140, emoji: "🥬", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 24 },
  { id: "jungli-veg",           categoryId: "chinese-veg", name: "Jungli Veg",              description: "Rustic stir-fried vegetables with bold spices.",           price: 180, emoji: "🥦", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 25 },
  { id: "crispy-veg",           categoryId: "chinese-veg", name: "Crispy Veg",              description: "Assorted crispy fried vegetables.",                       price: 160, emoji: "🥦", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 26 },
  { id: "bin-chilli",           categoryId: "chinese-veg", name: "Bin Chilli",              description: "French beans stir-fried in chilli sauce.",                price: 130, emoji: "🫘", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 27 },
  { id: "chana-roast",          categoryId: "chinese-veg", name: "Chana Roast",             description: "Roasted chickpeas with tangy seasoning.",                 price: 150, emoji: "🫘", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 28 },
  { id: "sabu-dana-khichdi",    categoryId: "chinese-veg", name: "Sabu Dana Khichdi",       description: "Sabudana cooked with peanuts and mild spices.",           price: 60,  emoji: "🍽️", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 29 },
  { id: "sabu-dana-bada",       categoryId: "chinese-veg", name: "Sabu Dana Bada (6 pc)",   description: "Crispy sabudana fritters.",                               price: 80,  emoji: "🍽️", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 30 },

  // ── CHINESE (NON-VEG) ────────────────────────────────────────
  { id: "chicken-chilli",         categoryId: "chinese-nonveg", name: "Chicken Chilli",           description: "Crispy chicken tossed in spicy chilli sauce.",         price: 250, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 3, tags: ["bestseller"], sortOrder: 1 },
  { id: "chicken-65",             categoryId: "chinese-nonveg", name: "Chicken 65",               description: "Fiery South-Indian style fried chicken with curry leaves.", price: 270, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 3, tags: ["bestseller"], sortOrder: 2 },
  { id: "chicken-lollipop",       categoryId: "chinese-nonveg", name: "Chicken Lollipop",         description: "Crispy chicken wings shaped into lollipops.",          price: 280, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 2, tags: ["bestseller"], sortOrder: 3 },
  { id: "chicken-hot-garlic",     categoryId: "chinese-nonveg", name: "Chicken Hot Garlic",       description: "Chicken in a bold hot garlic sauce.",                  price: 299, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 3, sortOrder: 4 },
  { id: "chicken-majestic",       categoryId: "chinese-nonveg", name: "Chicken Majestic",         description: "Crispy chicken in a signature majestic sauce.",        price: 320, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 2, tags: ["chef-special"], sortOrder: 5 },
  { id: "chicken-salt-pepper",    categoryId: "chinese-nonveg", name: "Chicken Salt & Pepper",    description: "Crispy chicken seasoned with salt and pepper.",        price: 299, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 1, sortOrder: 6 },
  { id: "chicken-lollipop-large", categoryId: "chinese-nonveg", name: "Chicken Lollipop (Large)", description: "Large portion of crispy chicken lollipops.",           price: 350, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 7 },
  { id: "egg-chilli",             categoryId: "chinese-nonveg", name: "Egg Chilli",               description: "Scrambled egg tossed in chilli sauce.",               price: 200, emoji: "🥚", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 8 },
  { id: "egg-65",                 categoryId: "chinese-nonveg", name: "Egg 65",                   description: "Spiced fried egg, South-Indian 65 style.",            price: 210, emoji: "🥚", isVeg: false, isAvailable: true, spiceLevel: 3, sortOrder: 9 },

  // ── CONTINENTAL ──────────────────────────────────────────────
  { id: "cheese-pizza",         categoryId: "continental", name: "Cheese Pizza",         description: "Classic pizza topped with melted cheese.",                price: 170, emoji: "🍕", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 1 },
  { id: "veg-cheese-pizza",     categoryId: "continental", name: "Veg Cheese Pizza",     description: "Loaded vegetable pizza with cheese.",                     price: 180, emoji: "🍕", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 2 },
  { id: "double-cheese-pizza",  categoryId: "continental", name: "Double Cheese Pizza",  description: "Extra cheesy pizza for cheese lovers.",                   price: 230, emoji: "🍕", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 3 },
  { id: "chef-special-pizza",   categoryId: "continental", name: "Chef Special Pizza",   description: "Chef's signature pizza with a special topping mix.",     price: 250, emoji: "🍕", isVeg: true, isAvailable: true, spiceLevel: 1, tags: ["chef-special"], sortOrder: 4 },
  { id: "mexican-pizza",        categoryId: "continental", name: "Mexican Pizza",         description: "Spicy Mexican-style pizza with jalapeños.",              price: 210, emoji: "🍕", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 5 },
  { id: "paneer-pizza",         categoryId: "continental", name: "Paneer Pizza",          description: "Pizza loaded with marinated paneer chunks.",             price: 210, emoji: "🍕", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 6 },
  { id: "paneer-corn-pizza",    categoryId: "continental", name: "Paneer Corn Pizza",     description: "Paneer and sweet corn pizza.",                          price: 220, emoji: "🍕", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 7 },
  { id: "corn-pizza",           categoryId: "continental", name: "Corn Pizza",            description: "Sweet corn pizza.",                                     price: 200, emoji: "🍕", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 8 },
  { id: "veg-sandwich",         categoryId: "continental", name: "Veg Sandwich",          description: "Fresh vegetable sandwich.",                             price: 60,  emoji: "🥪", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 9 },
  { id: "veg-cheese-sandwich",  categoryId: "continental", name: "Veg Cheese Sandwich",   description: "Toasted sandwich with vegetables and melted cheese.",   price: 70,  emoji: "🥪", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 10 },
  { id: "mexican-sandwich",     categoryId: "continental", name: "Mexican Sandwich",      description: "Spicy Mexican-style vegetable sandwich.",               price: 80,  emoji: "🥪", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 11 },

  // ── TANDOOR (VEG) ────────────────────────────────────────────
  { id: "paneer-tikka",          categoryId: "tandoor-veg", name: "Paneer Tikka",           description: "Char-grilled cottage cheese marinated in yogurt and spices.", price: 230, emoji: "🧀", isVeg: true, isAvailable: true, spiceLevel: 2, tags: ["bestseller"], sortOrder: 1 },
  { id: "paneer-achari-tikka",   categoryId: "tandoor-veg", name: "Paneer Achari Tikka",    description: "Paneer in a tangy pickle-spiced marinade.",                   price: 230, emoji: "🧀", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 2 },
  { id: "paneer-lasooni-tikka",  categoryId: "tandoor-veg", name: "Paneer Lasooni Tikka",   description: "Garlic-marinated paneer tikka.",                              price: 230, emoji: "🧀", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 3 },
  { id: "paneer-pudina-tikka",   categoryId: "tandoor-veg", name: "Paneer Pudina Tikka",    description: "Paneer in a fresh mint marinade.",                            price: 240, emoji: "🧀", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 4 },
  { id: "paneer-hariyali-tikka", categoryId: "tandoor-veg", name: "Paneer Hariyali Tikka",  description: "Paneer in a vibrant green herb marinade.",                    price: 240, emoji: "🧀", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 5 },
  { id: "paneer-kalimirch-tikka",categoryId: "tandoor-veg", name: "Paneer Kali Mirch Tikka",description: "Paneer marinated with black pepper.",                        price: 250, emoji: "🧀", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 6 },
  { id: "pineapple-tikka",       categoryId: "tandoor-veg", name: "Pineapple Tikka",        description: "Sweet pineapple chunks grilled in the tandoor.",             price: 250, emoji: "🍍", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 7 },
  { id: "mushroom-tikka",        categoryId: "tandoor-veg", name: "Mushroom Tikka",         description: "Marinated mushrooms grilled in the clay oven.",              price: 250, emoji: "🍄", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 8 },
  { id: "baby-corn-tikka",       categoryId: "tandoor-veg", name: "Baby Corn Tikka",        description: "Grilled baby corn with tandoori seasoning.",                 price: 200, emoji: "🌽", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 9 },
  { id: "aloo-adrak-tikki",      categoryId: "tandoor-veg", name: "Aloo Adrak Tikki",       description: "Crispy potato and ginger patties.",                          price: 160, emoji: "🥔", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 10 },
  { id: "hara-bhara-kebab",      categoryId: "tandoor-veg", name: "Hara Bhara Kebab",       description: "Green spinach and pea kebabs, soft inside.",                price: 180, emoji: "🥦", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 11 },
  { id: "cheese-chaska-kebab",   categoryId: "tandoor-veg", name: "Cheese Chaska Kebab",    description: "Cheesy vegetable kebab with a smoky char.",                 price: 220, emoji: "🧀", isVeg: true, isAvailable: true, spiceLevel: 1, tags: ["chef-special"], sortOrder: 12 },

  // ── TANDOOR (NON-VEG) ────────────────────────────────────────
  { id: "tandoori-chicken",       categoryId: "tandoor-nonveg", name: "Tandoori Chicken (4 pc)", description: "Clay-oven roasted chicken in a smoky tandoori marinade.",     price: 250, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 2, tags: ["bestseller"], sortOrder: 1 },
  { id: "chicken-tikka",          categoryId: "tandoor-nonveg", name: "Chicken Tikka",           description: "Boneless chicken pieces marinated and grilled in the tandoor.", price: 299, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 2, tags: ["bestseller"], sortOrder: 2 },
  { id: "chicken-malai-tikka",    categoryId: "tandoor-nonveg", name: "Chicken Malai Tikka",     description: "Creamy, melt-in-your-mouth chicken tikka.",                    price: 310, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 1, sortOrder: 3 },
  { id: "chicken-afghani-tikka",  categoryId: "tandoor-nonveg", name: "Chicken Afghani Tikka",   description: "Rich cream and cashew-marinated chicken tikka.",               price: 300, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 1, sortOrder: 4 },
  { id: "chicken-achari-tikka",   categoryId: "tandoor-nonveg", name: "Chicken Achari Tikka",    description: "Chicken tikka in a bold pickle-spiced marinade.",              price: 300, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 5 },
  { id: "chicken-ginger-tikka",   categoryId: "tandoor-nonveg", name: "Chicken Ginger Tikka",    description: "Chicken tikka with a fresh ginger kick.",                      price: 250, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 6 },
  { id: "chicken-pahadi-tikka",   categoryId: "tandoor-nonveg", name: "Chicken Pahadi Tikka",    description: "Green herb-marinated chicken from the hills.",                 price: 350, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 1, sortOrder: 7 },
  { id: "chicken-pudina-tikka",   categoryId: "tandoor-nonveg", name: "Chicken Pudina Tikka",    description: "Chicken tikka marinated with fresh mint.",                     price: 330, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 1, sortOrder: 8 },
  { id: "chicken-kali-mirch-tikka",categoryId:"tandoor-nonveg", name: "Chicken Kali Mirch Tikka","description": "Chicken tikka seasoned with black pepper.",                price: 310, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 9 },
  { id: "chicken-hasmukh-tikka",  categoryId: "tandoor-nonveg", name: "Chicken Hasmukh Tikka",   description: "Chef's special Hasmukh-style chicken tikka.",                  price: 250, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 2, tags: ["chef-special"], sortOrder: 10 },
  { id: "chicken-lasooni",        categoryId: "tandoor-nonveg", name: "Chicken Lasooni",          description: "Garlic-marinated chicken grilled to perfection.",              price: 320, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 11 },
  { id: "chicken-roast",          categoryId: "tandoor-nonveg", name: "Chicken Roast (4 pc)",     description: "Tandoor-roasted chicken pieces, crispy outside, juicy inside.", price: 240, emoji: "🍗", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 12 },

  // ── ROTI SPECIAL ─────────────────────────────────────────────
  { id: "tawa-roti",          categoryId: "roti", name: "Tawa Roti",          description: "Whole-wheat flatbread made on the tawa.",           price: 10, emoji: "🫓", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 1 },
  { id: "tawa-butter-roti",   categoryId: "roti", name: "Tawa Butter Roti",   description: "Tawa roti brushed with butter.",                    price: 20, emoji: "🫓", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 2 },
  { id: "tandoor-roti",       categoryId: "roti", name: "Tandoor Roti",       description: "Whole-wheat flatbread fresh from the clay oven.",   price: 10, emoji: "🫓", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 3 },
  { id: "tandoor-butter-roti",categoryId: "roti", name: "Tandoor Butter Roti",description: "Clay-oven roti brushed with butter.",               price: 20, emoji: "🫓", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 4 },
  { id: "laccha-paratha",     categoryId: "roti", name: "Laccha Paratha",     description: "Layered, flaky whole-wheat paratha.",               price: 50, emoji: "🫓", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 5 },
  { id: "plain-naan",         categoryId: "roti", name: "Plain Naan",         description: "Soft leavened bread from the tandoor.",             price: 35, emoji: "🫓", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 6 },
  { id: "butter-naan",        categoryId: "roti", name: "Butter Naan",        description: "Soft, fluffy naan brushed with butter.",            price: 40, emoji: "🫓", isVeg: true, isAvailable: true, spiceLevel: 0, tags: ["bestseller"], sortOrder: 7 },
  { id: "cheese-garlic-naan", categoryId: "roti", name: "Cheese Garlic Naan", description: "Naan topped with garlic and melted cheese.",       price: 70, emoji: "🫓", isVeg: true, isAvailable: true, spiceLevel: 0, tags: ["bestseller"], sortOrder: 8 },
  { id: "masala-kulcha",      categoryId: "roti", name: "Masala Kulcha",      description: "Leavened bread stuffed with spiced masala.",        price: 60, emoji: "🫓", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 9 },
  { id: "pudina-kulcha",      categoryId: "roti", name: "Pudina Kulcha",      description: "Mint-flavoured leavened kulcha.",                   price: 60, emoji: "🫓", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 10 },
  { id: "onion-kulcha",       categoryId: "roti", name: "Onion Kulcha",       description: "Kulcha stuffed with caramelised onions.",           price: 60, emoji: "🫓", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 11 },

  // ── MAIN COURSE (VEG) ────────────────────────────────────────
  { id: "steamed-rice",           categoryId: "main-veg", name: "Steamed Rice",            description: "Plain steamed basmati rice.",                                  price: 80,  emoji: "🍚", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 1 },
  { id: "jeera-rice",             categoryId: "main-veg", name: "Jeera Rice",              description: "Basmati rice tempered with cumin.",                           price: 100, emoji: "🍚", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 2 },
  { id: "onion-tomato-rice",      categoryId: "main-veg", name: "Onion Tomato Rice",       description: "Spiced rice cooked with onion and tomato.",                   price: 120, emoji: "🍚", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 3 },
  { id: "masala-rice",            categoryId: "main-veg", name: "Masala Rice",             description: "Flavourful spiced rice.",                                      price: 130, emoji: "🍚", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 4 },
  { id: "veg-pulao",              categoryId: "main-veg", name: "Veg Pulao",               description: "Aromatic basmati rice cooked with vegetables.",               price: 130, emoji: "🍚", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 5 },
  { id: "veg-biryani",            categoryId: "main-veg", name: "Veg Biryani",             description: "Fragrant dum-cooked rice with seasonal vegetables.",          price: 160, emoji: "🍚", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 6 },
  { id: "dal-khichdi",            categoryId: "main-veg", name: "Dal Khichdi",             description: "Comforting rice and lentil one-pot dish.",                    price: 150, emoji: "🥣", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 7 },
  { id: "masala-khichdi",         categoryId: "main-veg", name: "Masala Khichdi",          description: "Spiced dal and rice khichdi.",                                price: 160, emoji: "🥣", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 8 },
  { id: "dal-plain",              categoryId: "main-veg", name: "Dal Plain",               description: "Simple boiled yellow dal.",                                   price: 80,  emoji: "🥘", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 9 },
  { id: "dal-fry",                categoryId: "main-veg", name: "Dal Fry",                 description: "Yellow lentils finished with a sizzling ghee tempering.",     price: 120, emoji: "🥘", isVeg: true, isAvailable: true, spiceLevel: 1, tags: ["bestseller"], sortOrder: 10 },
  { id: "dal-tadka",              categoryId: "main-veg", name: "Dal Tadka",               description: "Lentils with a bold aromatic tadka.",                        price: 130, emoji: "🥘", isVeg: true, isAvailable: true, spiceLevel: 1, tags: ["bestseller"], sortOrder: 11 },
  { id: "dal-do-pyaza",           categoryId: "main-veg", name: "Dal Do Pyaza",            description: "Dal cooked with double onions.",                             price: 140, emoji: "🥘", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 12 },
  { id: "jeera-dal",              categoryId: "main-veg", name: "Jeera Dal",               description: "Lentils tempered with cumin.",                               price: 110, emoji: "🥘", isVeg: true, isAvailable: true, spiceLevel: 0, sortOrder: 13 },
  { id: "dal-makhani",            categoryId: "main-veg", name: "Dal Makhani",             description: "Slow-cooked black lentils in a rich buttery gravy.",         price: 180, emoji: "🥘", isVeg: true, isAvailable: true, spiceLevel: 1, tags: ["bestseller"], sortOrder: 14 },
  { id: "paneer-masala",          categoryId: "main-veg", name: "Paneer Masala",           description: "Paneer in a flavourful masala gravy.",                       price: 180, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 15 },
  { id: "paneer-butter-masala",   categoryId: "main-veg", name: "Paneer Butter Masala",    description: "Cottage cheese in a rich, creamy tomato-cashew gravy.",     price: 230, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 1, tags: ["bestseller"], sortOrder: 16 },
  { id: "paneer-do-pyaza",        categoryId: "main-veg", name: "Paneer Do Pyaza",         description: "Paneer with double onions in a spiced gravy.",              price: 230, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 17 },
  { id: "paneer-sahuji",          categoryId: "main-veg", name: "Paneer Sahuji",           description: "Chhattisgarh-style paneer preparation.",                    price: 230, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 2, tags: ["local"], sortOrder: 18 },
  { id: "paneer-kadhai-tadka",    categoryId: "main-veg", name: "Paneer Kadhai Tadka",     description: "Paneer cooked in a kadhai with pepper and spices.",         price: 240, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 19 },
  { id: "paneer-punjabi-masala",  categoryId: "main-veg", name: "Paneer Punjabi Masala",   description: "Rich Punjabi-style paneer.",                                price: 250, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 20 },
  { id: "paneer-lababdar",        categoryId: "main-veg", name: "Paneer Lababdar Masala",  description: "Paneer in a velvety, indulgent gravy.",                     price: 250, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 1, tags: ["chef-special"], sortOrder: 21 },
  { id: "paneer-lachhedar",       categoryId: "main-veg", name: "Paneer Lachhedar Masala", description: "Paneer with layered spiced gravy.",                         price: 260, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 22 },
  { id: "paneer-tikka-masala",    categoryId: "main-veg", name: "Paneer Tikka Masala",     description: "Grilled paneer tikka in a smoky masala gravy.",             price: 280, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 23 },
  { id: "paneer-kofta-masala",    categoryId: "main-veg", name: "Paneer Kofta Masala",     description: "Paneer and vegetable kofta balls in a rich gravy.",         price: 280, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 24 },
  { id: "palak-paneer",           categoryId: "main-veg", name: "Palak Paneer",            description: "Paneer in a creamy spinach gravy.",                         price: 190, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 1, tags: ["bestseller"], sortOrder: 25 },
  { id: "paneer-bhurji",          categoryId: "main-veg", name: "Paneer Bhurji",           description: "Scrambled paneer with onion, tomato and spices.",           price: 200, emoji: "🍳", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 26 },
  { id: "kaju-masala",            categoryId: "main-veg", name: "Kaju Masala",             description: "Cashew nuts in a rich and creamy masala gravy.",            price: 300, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 1, tags: ["chef-special"], sortOrder: 27 },
  { id: "soya-chaap-masala",      categoryId: "main-veg", name: "Soya Chaap Masala",       description: "Soya chaap cooked in a spiced masala gravy.",               price: 260, emoji: "🍢", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 28 },
  { id: "mushroom-masala",        categoryId: "main-veg", name: "Mushroom Masala",         description: "Mushrooms in a spiced tomato-based masala.",               price: 260, emoji: "🍄", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 29 },
  { id: "mushroom-kadhai",        categoryId: "main-veg", name: "Mushroom Kadhai",         description: "Mushrooms cooked kadhai-style with peppers.",              price: 260, emoji: "🍄", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 30 },
  { id: "veg-kadhai",             categoryId: "main-veg", name: "Veg Kadhai",              description: "Mixed vegetables cooked kadhai-style.",                    price: 260, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 31 },
  { id: "mix-veg",                categoryId: "main-veg", name: "Mix Veg",                 description: "Seasonal vegetables in a spiced gravy.",                   price: 170, emoji: "🥦", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 32 },
  { id: "veg-keema",              categoryId: "main-veg", name: "Veg Keema",               description: "Finely minced vegetable keema.",                           price: 170, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 33 },
  { id: "veg-khasta",             categoryId: "main-veg", name: "Veg Khasta",              description: "Crispy fried vegetables in a light gravy.",                price: 170, emoji: "🥦", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 34 },
  { id: "veg-jaipuri",            categoryId: "main-veg", name: "Veg Jaipuri",             description: "Rajasthani-style vegetable curry.",                        price: 160, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 35 },
  { id: "aloo-gobhi-matar",       categoryId: "main-veg", name: "Aloo Gobhi Matar",        description: "Potato, cauliflower and peas in a dry masala.",            price: 180, emoji: "🥔", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 36 },
  { id: "gobhi-masala",           categoryId: "main-veg", name: "Gobhi Masala",            description: "Cauliflower cooked in a spiced masala.",                   price: 150, emoji: "🥦", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 37 },
  { id: "aloo-dum-punjabi",       categoryId: "main-veg", name: "Aloo Dum Punjabi",        description: "Baby potatoes slow-cooked in Punjabi dum style.",          price: 180, emoji: "🥔", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 38 },
  { id: "aloo-dum-chingari",      categoryId: "main-veg", name: "Aloo Dum Chingari",       description: "Baby potatoes in a fiery Chingari masala.",                price: 170, emoji: "🥔", isVeg: true, isAvailable: true, spiceLevel: 3, tags: ["local"], sortOrder: 39 },
  { id: "bhindi-masala",          categoryId: "main-veg", name: "Bhindi Masala",           description: "Okra stir-fried with spices.",                             price: 190, emoji: "🍽️", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 40 },
  { id: "bhindi-kurkure",         categoryId: "main-veg", name: "Bhindi Kurkure",          description: "Crispy fried okra with tangy seasoning.",                  price: 180, emoji: "🍽️", isVeg: true, isAvailable: true, spiceLevel: 1, sortOrder: 41 },
  { id: "veg-kolhapuri",          categoryId: "main-veg", name: "Veg Kolhapuri",           description: "Fiery Kolhapuri-style vegetable curry.",                   price: 180, emoji: "🍛", isVeg: true, isAvailable: true, spiceLevel: 3, sortOrder: 42 },
  { id: "papad-churi",            categoryId: "main-veg", name: "Papad Churi",             description: "Crushed papad cooked in a spiced masala.",                 price: 180, emoji: "🍽️", isVeg: true, isAvailable: true, spiceLevel: 2, sortOrder: 43 },

  // ── MAIN COURSE (NON-VEG) ────────────────────────────────────
  { id: "chicken-masala",          categoryId: "main-nonveg", name: "Chicken Masala (4 pc)",          description: "Chicken pieces in a rich, spiced masala gravy.",          price: 300, emoji: "🍲", isVeg: false, isAvailable: true, spiceLevel: 2, tags: ["bestseller"], sortOrder: 1 },
  { id: "chicken-butter-masala",   categoryId: "main-nonveg", name: "Chicken Butter Masala (4 pc)",   description: "Tender chicken in a velvety buttery tomato gravy.",        price: 350, emoji: "🍲", isVeg: false, isAvailable: true, spiceLevel: 1, tags: ["bestseller"], sortOrder: 2 },
  { id: "chicken-tikka-masala-m",  categoryId: "main-nonveg", name: "Chicken Tikka Masala (4 pc)",    description: "Grilled chicken tikka in a smoky masala gravy.",          price: 300, emoji: "🍲", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 3 },
  { id: "chicken-kadhai",          categoryId: "main-nonveg", name: "Chicken Kadhai (4 pc)",          description: "Chicken cooked with bell peppers and freshly ground spices.", price: 300, emoji: "🍲", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 4 },
  { id: "chicken-curry",           categoryId: "main-nonveg", name: "Chicken Curry (4 pc)",           description: "Classic home-style chicken curry.",                        price: 280, emoji: "🍲", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 5 },
  { id: "chicken-rara",            categoryId: "main-nonveg", name: "Chicken Rara (4 pc)",            description: "Chicken cooked with minced chicken — bold and rustic.",    price: 350, emoji: "🍲", isVeg: false, isAvailable: true, spiceLevel: 3, sortOrder: 6 },
  { id: "chicken-punjabi",         categoryId: "main-nonveg", name: "Chicken Punjabi (4 pc)",         description: "Punjabi-style chicken in a hearty gravy.",                price: 320, emoji: "🍲", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 7 },
  { id: "chicken-kolhapuri",       categoryId: "main-nonveg", name: "Chicken Kolhapuri (4 pc)",       description: "Fiery Kolhapuri-style chicken curry.",                    price: 280, emoji: "🍲", isVeg: false, isAvailable: true, spiceLevel: 3, sortOrder: 8 },
  { id: "chicken-bhuna",           categoryId: "main-nonveg", name: "Chicken Bhuna (4 pc)",           description: "Slow-roasted chicken in a thick, dry masala.",            price: 300, emoji: "🍲", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 9 },
  { id: "chicken-dehati",          categoryId: "main-nonveg", name: "Chicken Dehati (4 pc)",          description: "Rustic village-style chicken preparation.",               price: 250, emoji: "🍲", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 10 },
  { id: "chicken-tandoori-masala", categoryId: "main-nonveg", name: "Chicken Tandoori Masala (4 pc)", description: "Tandoor-finished chicken in a smoky masala.",             price: 320, emoji: "🍲", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 11 },

  // ── BIRYANI SPECIAL ──────────────────────────────────────────
  { id: "chicken-dum-biryani",        categoryId: "biryani", name: "Chicken Dum Biryani (Full)",        description: "Layered basmati and chicken slow-cooked on dum.",           price: 220, emoji: "🍛", isVeg: false, isAvailable: true, spiceLevel: 2, tags: ["bestseller"], sortOrder: 1 },
  { id: "chicken-hyderabadi-biryani", categoryId: "biryani", name: "Chicken Hyderabadi Biryani (Full)", description: "Aromatic Hyderabadi dum biryani with whole spices.",         price: 230, emoji: "🍛", isVeg: false, isAvailable: true, spiceLevel: 2, tags: ["bestseller"], sortOrder: 2 },
  { id: "chicken-roast-biryani",      categoryId: "biryani", name: "Chicken Roast Biryani (Full)",      description: "Biryani with tandoor-roasted chicken.",                     price: 250, emoji: "🍛", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 3 },
  { id: "chicken-tandoori-biryani",   categoryId: "biryani", name: "Chicken Tandoori Biryani (Full)",   description: "Biryani with smoky tandoori chicken.",                      price: 250, emoji: "🍛", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 4 },
  { id: "egg-biryani",                categoryId: "biryani", name: "Egg Biryani (Full)",                description: "Fragrant basmati rice with spiced boiled eggs.",            price: 180, emoji: "🍚", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 5 },
  { id: "fish-biryani",               categoryId: "biryani", name: "Fish Biryani (Full)",               description: "Fragrant dum biryani with tender fish.",                    price: 200, emoji: "🍚", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 6 },
  { id: "mutton-biryani",             categoryId: "biryani", name: "Mutton Biryani (Full)",             description: "Rich slow-cooked mutton biryani.",                          price: 350, emoji: "🍛", isVeg: false, isAvailable: true, spiceLevel: 2, tags: ["chef-special"], sortOrder: 7 },
  { id: "veg-biryani-b",              categoryId: "biryani", name: "Veg Biryani",                       description: "Fragrant dum-cooked rice with seasonal vegetables.",        price: 160, emoji: "🍚", isVeg: true,  isAvailable: true, spiceLevel: 2, sortOrder: 8 },

  // ── MUTTON SPECIAL ───────────────────────────────────────────
  { id: "mutton-curry",      categoryId: "mutton", name: "Mutton Curry (4 pc)",      description: "Classic mutton curry slow-cooked with whole spices.", price: 360, emoji: "🥩", isVeg: false, isAvailable: true, spiceLevel: 2, tags: ["bestseller"], sortOrder: 1 },
  { id: "mutton-masala",     categoryId: "mutton", name: "Mutton Masala (4 pc)",     description: "Mutton cooked in a rich, bold masala.",              price: 380, emoji: "🥩", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 2 },
  { id: "mutton-rogan-josh", categoryId: "mutton", name: "Mutton Rogan Josh (4 pc)", description: "Kashmiri-style mutton in a deep aromatic gravy.",    price: 410, emoji: "🥩", isVeg: false, isAvailable: true, spiceLevel: 2, tags: ["chef-special"], sortOrder: 3 },

  // ── FISH SPECIAL ─────────────────────────────────────────────
  { id: "fish-fry",    categoryId: "fish", name: "Fish Fry (4 pc)",    description: "Crispy golden fried fish fillets.",                  price: 230, emoji: "🐟", isVeg: false, isAvailable: true, spiceLevel: 2, tags: ["bestseller"], sortOrder: 1 },
  { id: "fish-roast",  categoryId: "fish", name: "Fish Roast (4 pc)",  description: "Tandoor-roasted fish with a smoky char.",           price: 240, emoji: "🐟", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 2 },
  { id: "fish-curry",  categoryId: "fish", name: "Fish Curry (4 pc)",  description: "Traditional fish curry with local spices.",         price: 260, emoji: "🐟", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 3 },
  { id: "fish-masala", categoryId: "fish", name: "Fish Masala (4 pc)", description: "Fish cooked in a bold masala gravy.",              price: 280, emoji: "🐟", isVeg: false, isAvailable: true, spiceLevel: 2, sortOrder: 4 },
  { id: "fish-lapeta", categoryId: "fish", name: "Fish Lapeta",         description: "Chhattisgarhi-style spicy fish preparation.",      price: 300, emoji: "🐟", isVeg: false, isAvailable: true, spiceLevel: 3, tags: ["local", "chef-special"], sortOrder: 5 },

  // ── BEVERAGES & SHAKES ───────────────────────────────────────
  { id: "fresh-lime-soda",        categoryId: "beverages", name: "Fresh Lime Soda",            description: "Sweet-and-salty fresh lime soda.",              price: 40,  emoji: "🥤", isVeg: true, isAvailable: true, sortOrder: 1 },
  { id: "fresh-lime-water",       categoryId: "beverages", name: "Fresh Lime Water",           description: "Refreshing fresh lime with water.",             price: 50,  emoji: "🍋", isVeg: true, isAvailable: true, sortOrder: 2 },
  { id: "butter-milk",            categoryId: "beverages", name: "Butter Milk",                description: "Chilled spiced buttermilk.",                    price: 50,  emoji: "🥛", isVeg: true, isAvailable: true, sortOrder: 3 },
  { id: "lassi",                  categoryId: "beverages", name: "Lassi",                      description: "Thick, chilled sweet yogurt drink.",            price: 50,  emoji: "🥛", isVeg: true, isAvailable: true, sortOrder: 4 },
  { id: "green-mojito",           categoryId: "beverages", name: "Green Mojito",               description: "Minty fresh mocktail.",                         price: 80,  emoji: "🍹", isVeg: true, isAvailable: true, sortOrder: 5 },
  { id: "blue-lagoon",            categoryId: "beverages", name: "Blue Lagoon",                description: "Refreshing blue mocktail.",                     price: 80,  emoji: "🍹", isVeg: true, isAvailable: true, sortOrder: 6 },
  { id: "orange-shake",           categoryId: "beverages", name: "Orange Shake",               description: "Fresh orange milkshake.",                       price: 80,  emoji: "🍊", isVeg: true, isAvailable: true, sortOrder: 7 },
  { id: "pineapple-shake",        categoryId: "beverages", name: "Pineapple Shake",            description: "Tropical pineapple milkshake.",                 price: 80,  emoji: "🍍", isVeg: true, isAvailable: true, sortOrder: 8 },
  { id: "cold-coffee",            categoryId: "beverages", name: "Cold Coffee",                description: "Chilled blended coffee.",                       price: 80,  emoji: "☕", isVeg: true, isAvailable: true, sortOrder: 9 },
  { id: "mango-shake",            categoryId: "beverages", name: "Mango Shake",                description: "Creamy mango milkshake.",                       price: 110, emoji: "🥭", isVeg: true, isAvailable: true, sortOrder: 10 },
  { id: "strawberry-shake",       categoryId: "beverages", name: "Strawberry Shake",           description: "Fresh strawberry milkshake.",                   price: 110, emoji: "🍓", isVeg: true, isAvailable: true, sortOrder: 11 },
  { id: "chocolate-shake",        categoryId: "beverages", name: "Chocolate Shake",            description: "Rich chocolate milkshake.",                     price: 110, emoji: "🍫", isVeg: true, isAvailable: true, sortOrder: 12 },
  { id: "oreo-shake",             categoryId: "beverages", name: "Oreo Shake",                 description: "Creamy Oreo cookie milkshake.",                 price: 110, emoji: "🍪", isVeg: true, isAvailable: true, sortOrder: 13 },
  { id: "kitkat-shake",           categoryId: "beverages", name: "KitKat Shake",               description: "KitKat blended milkshake.",                     price: 110, emoji: "🍫", isVeg: true, isAvailable: true, sortOrder: 14 },
  { id: "dry-fruit-shake",        categoryId: "beverages", name: "Dry Fruit Shake",            description: "Milkshake loaded with assorted dry fruits.",    price: 110, emoji: "🥛", isVeg: true, isAvailable: true, sortOrder: 15 },
  { id: "fruit-punch",            categoryId: "beverages", name: "Fruit Punch",                description: "Mixed fruit punch mocktail.",                   price: 110, emoji: "🍹", isVeg: true, isAvailable: true, sortOrder: 16 },
  { id: "cold-coffee-ice-cream",  categoryId: "beverages", name: "Cold Coffee with Ice Cream", description: "Cold coffee topped with a scoop of ice cream.", price: 110, emoji: "🍦", isVeg: true, isAvailable: true, sortOrder: 17 },

  // ── TEA & COFFEE ─────────────────────────────────────────────
  { id: "regular-tea",      categoryId: "tea-coffee", name: "Regular Tea",       description: "Classic milk tea.",                            price: 15, emoji: "🍵", isVeg: true, isAvailable: true, sortOrder: 1 },
  { id: "masala-tea",       categoryId: "tea-coffee", name: "Masala Tea",        description: "Spiced milk tea brewed with whole spices.",    price: 20, emoji: "🍵", isVeg: true, isAvailable: true, tags: ["bestseller"], sortOrder: 2 },
  { id: "adrak-elaichi-tea",categoryId: "tea-coffee", name: "Adrak Elaichi Tea", description: "Ginger and cardamom tea.",                     price: 20, emoji: "🍵", isVeg: true, isAvailable: true, sortOrder: 3 },
  { id: "black-lemon-tea",  categoryId: "tea-coffee", name: "Black Lemon Tea",   description: "Light and refreshing black tea with lemon.",   price: 20, emoji: "🍵", isVeg: true, isAvailable: true, sortOrder: 4 },
  { id: "jaggery-tea",      categoryId: "tea-coffee", name: "Jaggery Tea",       description: "Naturally sweetened tea with jaggery.",        price: 20, emoji: "🍵", isVeg: true, isAvailable: true, sortOrder: 5 },
  { id: "coffee",           categoryId: "tea-coffee", name: "Coffee",            description: "Hot brewed coffee.",                           price: 20, emoji: "☕", isVeg: true, isAvailable: true, sortOrder: 6 },

  // ── SWEETS & SALADS ─────────────────────────────────────────
  { id: "gulab-jamun",    categoryId: "sweets-salads", name: "Gulab Jamun (2 pc)", description: "Warm milk-solid dumplings in rose-cardamom syrup.", price: 30,  emoji: "🍩", isVeg: true, isAvailable: true, tags: ["bestseller"], sortOrder: 1 },
  { id: "rabdi-jalebi",   categoryId: "sweets-salads", name: "Rabdi Jalebi",       description: "Crispy jalebi served with thick rabdi.",             price: 100, emoji: "🍮", isVeg: true, isAvailable: true, tags: ["chef-special"], sortOrder: 2 },
  { id: "papad-dry",      categoryId: "sweets-salads", name: "Papad Dry",          description: "Plain roasted papad.",                               price: 10,  emoji: "🍽️", isVeg: true, isAvailable: true, sortOrder: 3 },
  { id: "papad-fry",      categoryId: "sweets-salads", name: "Papad Fry",          description: "Deep-fried crispy papad.",                           price: 15,  emoji: "🍽️", isVeg: true, isAvailable: true, sortOrder: 4 },
  { id: "papad-masala",   categoryId: "sweets-salads", name: "Papad Masala",       description: "Roasted papad topped with spiced masala.",           price: 30,  emoji: "🍽️", isVeg: true, isAvailable: true, sortOrder: 5 },
  { id: "onion-salad",    categoryId: "sweets-salads", name: "Onion Salad",        description: "Fresh onion salad with lemon and spices.",           price: 30,  emoji: "🥗", isVeg: true, isAvailable: true, sortOrder: 6 },
  { id: "green-salad",    categoryId: "sweets-salads", name: "Green Salad",        description: "Fresh garden salad.",                                price: 60,  emoji: "🥗", isVeg: true, isAvailable: true, sortOrder: 7 },
  { id: "kachumber-salad",categoryId: "sweets-salads", name: "Kachumber Salad",    description: "Finely chopped cucumber, tomato and onion salad.",   price: 40,  emoji: "🥗", isVeg: true, isAvailable: true, sortOrder: 8 },
  { id: "peanut-salad",   categoryId: "sweets-salads", name: "Peanut Salad",       description: "Spiced peanut salad.",                               price: 80,  emoji: "🥜", isVeg: true, isAvailable: true, sortOrder: 9 },
  { id: "boondi-raita",   categoryId: "sweets-salads", name: "Boondi Raita",       description: "Chilled yogurt with boondi and spices.",             price: 80,  emoji: "🥛", isVeg: true, isAvailable: true, sortOrder: 10 },
  { id: "veg-raita",      categoryId: "sweets-salads", name: "Veg Raita",          description: "Chilled yogurt with fresh vegetables.",             price: 70,  emoji: "🥛", isVeg: true, isAvailable: true, sortOrder: 11 },
];
