-- =============================================================
-- Sangwari — Full menu update (actual restaurant menu)
-- Run in Supabase SQL Editor.
-- Order history is safe: order_items stores name/price snapshots,
-- so deleting menu_items does NOT break past orders.
-- =============================================================

-- Clear existing menu data
TRUNCATE menu_items CASCADE;
TRUNCATE categories CASCADE;

-- ── Categories ──────────────────────────────────────────────
INSERT INTO categories (id, name, emoji, sort_order, is_active) VALUES
  ('breakfast',      'Breakfast',             '🍳', 1,  true),
  ('soups',          'Soups',                 '🥣', 2,  true),
  ('noodles',        'Noodles',               '🍜', 3,  true),
  ('chinese-veg',    'Chinese (Veg)',          '🥬', 4,  true),
  ('chinese-nonveg', 'Chinese (Non-Veg)',      '🍗', 5,  true),
  ('continental',    'Continental',            '🍕', 6,  true),
  ('tandoor-veg',    'Tandoor (Veg)',          '🧆', 7,  true),
  ('tandoor-nonveg', 'Tandoor (Non-Veg)',      '🍖', 8,  true),
  ('roti',           'Roti Special',           '🫓', 9,  true),
  ('main-veg',       'Main Course (Veg)',      '🍛', 10, true),
  ('main-nonveg',    'Main Course (Non-Veg)',  '🍲', 11, true),
  ('biryani',        'Biryani Special',        '🍚', 12, true),
  ('mutton',         'Mutton Special',         '🥩', 13, true),
  ('fish',           'Fish Special',           '🐟', 14, true),
  ('beverages',      'Beverages & Shakes',     '🥤', 15, true),
  ('tea-coffee',     'Tea & Coffee',           '☕', 16, true),
  ('sweets-salads',  'Sweets & Salads',        '🍮', 17, true);

-- ── Menu Items ───────────────────────────────────────────────
INSERT INTO menu_items
  (id, category_id, name, description, price, emoji, is_veg, is_available, spice_level, tags, sort_order)
VALUES

-- BREAKFAST
('chhole-bhature',    'breakfast', 'Chhole Bhature (2 pc)', 'Fluffy bhature served with spiced chickpea curry.',    80,  '🫓', true, true, 1, '{bestseller}', 1),
('aloo-paratha',      'breakfast', 'Aloo Paratha',          'Whole-wheat flatbread stuffed with spiced potato.',   40,  '🫓', true, true, 1, '{}', 2),
('paneer-paratha',    'breakfast', 'Paneer Paratha',        'Flatbread stuffed with fresh cottage cheese.',        50,  '🫓', true, true, 1, '{}', 3),
('gobhi-paratha',     'breakfast', 'Gobhi Paratha',         'Flatbread stuffed with spiced cauliflower.',         40,  '🫓', true, true, 1, '{}', 4),
('paratha',           'breakfast', 'Paratha',               'Plain whole-wheat flatbread.',                       50,  '🫓', true, true, 0, '{}', 5),
('plain-dosa',        'breakfast', 'Plain Dosa',            'Crispy South-Indian rice crepe.',                    30,  '🥞', true, true, 0, '{}', 6),
('masala-dosa',       'breakfast', 'Masala Dosa',           'Crispy dosa filled with spiced potato masala.',     40,  '🥞', true, true, 1, '{bestseller}', 7),
('cutting-dosa',      'breakfast', 'Cutting Dosa',          'Thick soft dosa cut into pieces.',                  50,  '🥞', true, true, 1, '{}', 8),
('chana-poha',        'breakfast', 'Chana Poha',            'Flattened rice tossed with chickpeas and spices.',  20,  '🍽️', true, true, 1, '{}', 9),
('palak-puri',        'breakfast', 'Palak Puri',            'Puffed spinach bread.',                             30,  '🍽️', true, true, 1, '{}', 10),
('methi-puri',        'breakfast', 'Methi Puri',            'Puffed fenugreek bread.',                           30,  '🍽️', true, true, 1, '{}', 11),

-- SOUPS (VEG)
('manchow-soup',         'soups', 'Manchow Soup',              'Thick Indo-Chinese soup with fried noodles.',          80,  '🥣', true, true, 2, '{}', 1),
('veg-hot-sour-soup',    'soups', 'Veg Hot & Sour Soup',       'Tangy and spicy clear vegetable soup.',                90,  '🥣', true, true, 2, '{}', 2),
('lemon-coriander-soup', 'soups', 'Lemon Coriander Soup',      'Fresh soup with lemon and coriander.',                 90,  '🥣', true, true, 1, '{}', 3),
('sweet-corn-soup',      'soups', 'Sweet Corn Soup',           'Creamy sweet corn soup.',                              90,  '🥣', true, true, 0, '{}', 4),
('tomato-soup',          'soups', 'Tomato Soup',               'Classic creamy tomato soup.',                          80,  '🥣', true, true, 0, '{}', 5),
('cream-mushroom-soup',  'soups', 'Cream Mushroom Soup',       'Rich creamy mushroom soup.',                           110, '🥣', true, true, 0, '{}', 6),
-- SOUPS (NON-VEG)
('chicken-manchow-soup',    'soups', 'Chicken Manchow Soup',         'Thick Manchow soup with shredded chicken.',       110, '🥣', false, true, 2, '{}', 7),
('chicken-hot-sour-soup',   'soups', 'Chicken Hot & Sour Soup',      'Spicy tangy soup with tender chicken.',           110, '🥣', false, true, 2, '{}', 8),
('chicken-lemon-coriander', 'soups', 'Chicken Lemon Coriander Soup', 'Light chicken soup with lemon.',                  120, '🥣', false, true, 1, '{}', 9),

-- NOODLES
('chicken-chowmein',         'noodles', 'Chicken Chowmein',          'Stir-fried noodles with chicken and vegetables.', 180, '🍜', false, true, 2, '{bestseller}', 1),
('chicken-hakka-noodles',    'noodles', 'Chicken Hakka Noodles',     'Classic Hakka noodles with chicken.',             180, '🍜', false, true, 2, '{}', 2),
('chicken-schezwan-noodles', 'noodles', 'Chicken Schezwan Noodles',  'Fiery Schezwan noodles with chicken.',            180, '🍜', false, true, 3, '{}', 3),
('egg-chowmein',             'noodles', 'Egg Chowmein',              'Stir-fried noodles with scrambled egg.',          140, '🍜', false, true, 2, '{}', 4),
('egg-hakka-noodles',        'noodles', 'Egg Hakka Noodles',         'Hakka noodles tossed with egg.',                  140, '🍜', false, true, 2, '{}', 5),
('egg-schezwan-noodles',     'noodles', 'Egg Schezwan Noodles',      'Spicy Schezwan noodles with egg.',                140, '🍜', false, true, 3, '{}', 6),

-- CHINESE VEG
('veg-noodles',         'chinese-veg', 'Veg Noodles',           'Stir-fried noodles with fresh vegetables.',            80,  '🍜', true, true, 1, '{}', 1),
('schezwan-noodles',    'chinese-veg', 'Schezwan Noodles',      'Spicy Schezwan noodles with vegetables.',              90,  '🍜', true, true, 3, '{}', 2),
('manchurian',          'chinese-veg', 'Manchurian',            'Crispy veg balls in tangy Manchurian sauce.',          110, '🥬', true, true, 2, '{bestseller}', 3),
('pasta-red',           'chinese-veg', 'Pasta Red',             'Penne pasta in tangy red tomato sauce.',               120, '🍝', true, true, 1, '{}', 4),
('pasta-white',         'chinese-veg', 'Pasta White',           'Creamy white sauce pasta.',                            130, '🍝', true, true, 0, '{}', 5),
('schezwan-rice',       'chinese-veg', 'Schezwan Rice',         'Fiery Schezwan fried rice.',                           90,  '🍚', true, true, 3, '{}', 6),
('veg-fried-rice',      'chinese-veg', 'Veg Fried Rice',        'Wok-tossed fried rice with vegetables.',               130, '🍚', true, true, 1, '{}', 7),
('veg-schezwan-rice',   'chinese-veg', 'Veg Schezwan Rice',     'Fried rice in spicy Schezwan sauce.',                  150, '🍚', true, true, 3, '{}', 8),
('french-fries',        'chinese-veg', 'French Fries',          'Crispy golden potato fries.',                          90,  '🍟', true, true, 0, '{}', 9),
('paneer-chilli',       'chinese-veg', 'Paneer Chilli',         'Crispy paneer tossed in chilli sauce.',                180, '🧀', true, true, 2, '{bestseller}', 10),
('paneer-65',           'chinese-veg', 'Paneer 65',             'Deep-fried spiced paneer.',                            190, '🧀', true, true, 3, '{}', 11),
('paneer-majestic',     'chinese-veg', 'Paneer Majestic',       'Crispy paneer in majestic sauce.',                     200, '🧀', true, true, 2, '{chef-special}', 12),
('paneer-dragon',       'chinese-veg', 'Paneer Dragon',         'Fiery dragon-sauce crispy paneer.',                    200, '🧀', true, true, 3, '{}', 13),
('mushroom-chilli',     'chinese-veg', 'Mushroom Chilli',       'Sautéed mushrooms in spicy chilli sauce.',             170, '🍄', true, true, 2, '{}', 14),
('mushroom-salt-pepper','chinese-veg', 'Mushroom Salt & Pepper','Crispy mushrooms with salt and pepper.',               180, '🍄', true, true, 1, '{}', 15),
('baby-corn-chilli',    'chinese-veg', 'Baby Corn Chilli',      'Crispy baby corn in chilli sauce.',                    180, '🌽', true, true, 2, '{}', 16),
('crispy-corn',         'chinese-veg', 'Crispy Corn',           'Golden crispy sweet corn.',                            160, '🌽', true, true, 1, '{}', 17),
('lovely-corn',         'chinese-veg', 'Lovely Corn',           'Sweet corn with butter and seasonings.',               150, '🌽', true, true, 1, '{}', 18),
('corn-salt-pepper',    'chinese-veg', 'Corn Salt & Pepper',    'Crunchy corn with salt and pepper.',                   160, '🌽', true, true, 1, '{}', 19),
('soya-chaap-65',       'chinese-veg', 'Soya Chaap 65',         'Crispy soya chaap, 65 style.',                         200, '🍢', true, true, 3, '{}', 20),
('chana-chilli',        'chinese-veg', 'Chana Chilli',          'Spiced chickpeas in chilli sauce.',                    150, '🫘', true, true, 2, '{}', 21),
('potato-honey-chilli', 'chinese-veg', 'Potato Honey Chilli',   'Crispy potato in honey chilli glaze.',                 140, '🥔', true, true, 2, '{}', 22),
('potato-chilli',       'chinese-veg', 'Potato Chilli',         'Crispy potato in chilli sauce.',                       120, '🥔', true, true, 2, '{}', 23),
('veg-bullet',          'chinese-veg', 'Veg Bullet',            'Stuffed vegetable bullets.',                           140, '🥬', true, true, 2, '{}', 24),
('jungli-veg',          'chinese-veg', 'Jungli Veg',            'Rustic stir-fried vegetables.',                        180, '🥦', true, true, 2, '{}', 25),
('crispy-veg',          'chinese-veg', 'Crispy Veg',            'Assorted crispy fried vegetables.',                    160, '🥦', true, true, 1, '{}', 26),
('bin-chilli',          'chinese-veg', 'Bin Chilli',            'French beans in chilli sauce.',                        130, '🫘', true, true, 2, '{}', 27),
('chana-roast',         'chinese-veg', 'Chana Roast',           'Roasted chickpeas with tangy seasoning.',              150, '🫘', true, true, 1, '{}', 28),
('sabu-dana-khichdi',   'chinese-veg', 'Sabu Dana Khichdi',     'Sabudana with peanuts and mild spices.',               60,  '🍽️', true, true, 0, '{}', 29),
('sabu-dana-bada',      'chinese-veg', 'Sabu Dana Bada (6 pc)', 'Crispy sabudana fritters.',                            80,  '🍽️', true, true, 1, '{}', 30),

-- CHINESE NON-VEG
('chicken-chilli',         'chinese-nonveg', 'Chicken Chilli',           'Crispy chicken in spicy chilli sauce.',          250, '🍗', false, true, 3, '{bestseller}', 1),
('chicken-65',             'chinese-nonveg', 'Chicken 65',               'Fiery South-Indian style fried chicken.',        270, '🍗', false, true, 3, '{bestseller}', 2),
('chicken-lollipop',       'chinese-nonveg', 'Chicken Lollipop',         'Crispy chicken lollipops.',                      280, '🍗', false, true, 2, '{bestseller}', 3),
('chicken-hot-garlic',     'chinese-nonveg', 'Chicken Hot Garlic',       'Chicken in bold hot garlic sauce.',              299, '🍗', false, true, 3, '{}', 4),
('chicken-majestic',       'chinese-nonveg', 'Chicken Majestic',         'Crispy chicken in majestic sauce.',              320, '🍗', false, true, 2, '{chef-special}', 5),
('chicken-salt-pepper',    'chinese-nonveg', 'Chicken Salt & Pepper',    'Crispy chicken with salt and pepper.',           299, '🍗', false, true, 1, '{}', 6),
('chicken-lollipop-large', 'chinese-nonveg', 'Chicken Lollipop (Large)', 'Large portion crispy chicken lollipops.',        350, '🍗', false, true, 2, '{}', 7),
('egg-chilli',             'chinese-nonveg', 'Egg Chilli',               'Egg tossed in chilli sauce.',                    200, '🥚', false, true, 2, '{}', 8),
('egg-65',                 'chinese-nonveg', 'Egg 65',                   'Spiced fried egg, 65 style.',                    210, '🥚', false, true, 3, '{}', 9),

-- CONTINENTAL
('cheese-pizza',        'continental', 'Cheese Pizza',        'Classic pizza with melted cheese.',                         170, '🍕', true, true, 0, '{}', 1),
('veg-cheese-pizza',    'continental', 'Veg Cheese Pizza',    'Vegetable pizza with cheese.',                              180, '🍕', true, true, 1, '{}', 2),
('double-cheese-pizza', 'continental', 'Double Cheese Pizza', 'Extra cheesy pizza.',                                       230, '🍕', true, true, 0, '{}', 3),
('chef-special-pizza',  'continental', 'Chef Special Pizza',  'Chef''s signature pizza.',                                  250, '🍕', true, true, 1, '{chef-special}', 4),
('mexican-pizza',       'continental', 'Mexican Pizza',       'Spicy Mexican-style pizza.',                                210, '🍕', true, true, 2, '{}', 5),
('paneer-pizza',        'continental', 'Paneer Pizza',        'Pizza loaded with marinated paneer.',                       210, '🍕', true, true, 1, '{}', 6),
('paneer-corn-pizza',   'continental', 'Paneer Corn Pizza',   'Paneer and sweet corn pizza.',                             220, '🍕', true, true, 1, '{}', 7),
('corn-pizza',          'continental', 'Corn Pizza',          'Sweet corn pizza.',                                         200, '🍕', true, true, 0, '{}', 8),
('veg-sandwich',        'continental', 'Veg Sandwich',        'Fresh vegetable sandwich.',                                 60,  '🥪', true, true, 0, '{}', 9),
('veg-cheese-sandwich', 'continental', 'Veg Cheese Sandwich', 'Toasted sandwich with vegetables and melted cheese.',       70,  '🥪', true, true, 0, '{}', 10),
('mexican-sandwich',    'continental', 'Mexican Sandwich',    'Spicy Mexican-style vegetable sandwich.',                   80,  '🥪', true, true, 2, '{}', 11),

-- TANDOOR VEG
('paneer-tikka',           'tandoor-veg', 'Paneer Tikka',            'Char-grilled cottage cheese in yogurt marinade.',   230, '🧀', true, true, 2, '{bestseller}', 1),
('paneer-achari-tikka',    'tandoor-veg', 'Paneer Achari Tikka',     'Paneer in tangy pickle-spiced marinade.',           230, '🧀', true, true, 2, '{}', 2),
('paneer-lasooni-tikka',   'tandoor-veg', 'Paneer Lasooni Tikka',    'Garlic-marinated paneer tikka.',                    230, '🧀', true, true, 2, '{}', 3),
('paneer-pudina-tikka',    'tandoor-veg', 'Paneer Pudina Tikka',     'Paneer in fresh mint marinade.',                    240, '🧀', true, true, 1, '{}', 4),
('paneer-hariyali-tikka',  'tandoor-veg', 'Paneer Hariyali Tikka',   'Paneer in vibrant green herb marinade.',            240, '🧀', true, true, 1, '{}', 5),
('paneer-kalimirch-tikka', 'tandoor-veg', 'Paneer Kali Mirch Tikka', 'Paneer marinated with black pepper.',               250, '🧀', true, true, 2, '{}', 6),
('pineapple-tikka',        'tandoor-veg', 'Pineapple Tikka',         'Sweet pineapple grilled in the tandoor.',           250, '🍍', true, true, 0, '{}', 7),
('mushroom-tikka',         'tandoor-veg', 'Mushroom Tikka',          'Marinated mushrooms grilled in clay oven.',         250, '🍄', true, true, 1, '{}', 8),
('baby-corn-tikka',        'tandoor-veg', 'Baby Corn Tikka',         'Grilled baby corn with tandoori seasoning.',        200, '🌽', true, true, 1, '{}', 9),
('aloo-adrak-tikki',       'tandoor-veg', 'Aloo Adrak Tikki',        'Crispy potato and ginger patties.',                 160, '🥔', true, true, 1, '{}', 10),
('hara-bhara-kebab',       'tandoor-veg', 'Hara Bhara Kebab',        'Green spinach and pea kebabs.',                     180, '🥦', true, true, 1, '{}', 11),
('cheese-chaska-kebab',    'tandoor-veg', 'Cheese Chaska Kebab',     'Cheesy vegetable kebab with smoky char.',           220, '🧀', true, true, 1, '{chef-special}', 12),

-- TANDOOR NON-VEG
('tandoori-chicken',        'tandoor-nonveg', 'Tandoori Chicken (4 pc)',    'Clay-oven roasted chicken, smoky marinade.',   250, '🍗', false, true, 2, '{bestseller}', 1),
('chicken-tikka',           'tandoor-nonveg', 'Chicken Tikka',              'Boneless chicken grilled in the tandoor.',     299, '🍗', false, true, 2, '{bestseller}', 2),
('chicken-malai-tikka',     'tandoor-nonveg', 'Chicken Malai Tikka',        'Creamy melt-in-your-mouth chicken tikka.',     310, '🍗', false, true, 1, '{}', 3),
('chicken-afghani-tikka',   'tandoor-nonveg', 'Chicken Afghani Tikka',      'Cream and cashew marinated chicken tikka.',    300, '🍗', false, true, 1, '{}', 4),
('chicken-achari-tikka',    'tandoor-nonveg', 'Chicken Achari Tikka',       'Chicken tikka in pickle-spiced marinade.',     300, '🍗', false, true, 2, '{}', 5),
('chicken-ginger-tikka',    'tandoor-nonveg', 'Chicken Ginger Tikka',       'Chicken tikka with fresh ginger kick.',        250, '🍗', false, true, 2, '{}', 6),
('chicken-pahadi-tikka',    'tandoor-nonveg', 'Chicken Pahadi Tikka',       'Green herb marinated mountain-style tikka.',   350, '🍗', false, true, 1, '{}', 7),
('chicken-pudina-tikka',    'tandoor-nonveg', 'Chicken Pudina Tikka',       'Chicken tikka with fresh mint.',               330, '🍗', false, true, 1, '{}', 8),
('chicken-kali-mirch-tikka','tandoor-nonveg', 'Chicken Kali Mirch Tikka',   'Chicken tikka with black pepper.',             310, '🍗', false, true, 2, '{}', 9),
('chicken-hasmukh-tikka',   'tandoor-nonveg', 'Chicken Hasmukh Tikka',      'Chef''s special Hasmukh tikka.',              250, '🍗', false, true, 2, '{chef-special}', 10),
('chicken-lasooni',         'tandoor-nonveg', 'Chicken Lasooni',             'Garlic-marinated chicken.',                    320, '🍗', false, true, 2, '{}', 11),
('chicken-roast',           'tandoor-nonveg', 'Chicken Roast (4 pc)',        'Tandoor-roasted chicken pieces.',              240, '🍗', false, true, 2, '{}', 12),

-- ROTI SPECIAL
('tawa-roti',          'roti', 'Tawa Roti',          'Whole-wheat flatbread on the tawa.',        10, '🫓', true, true, 0, '{}', 1),
('tawa-butter-roti',   'roti', 'Tawa Butter Roti',   'Tawa roti brushed with butter.',            20, '🫓', true, true, 0, '{}', 2),
('tandoor-roti',       'roti', 'Tandoor Roti',       'Flatbread fresh from the clay oven.',       10, '🫓', true, true, 0, '{}', 3),
('tandoor-butter-roti','roti', 'Tandoor Butter Roti','Clay-oven roti brushed with butter.',       20, '🫓', true, true, 0, '{}', 4),
('laccha-paratha',     'roti', 'Laccha Paratha',     'Layered flaky whole-wheat paratha.',        50, '🫓', true, true, 0, '{}', 5),
('plain-naan',         'roti', 'Plain Naan',         'Soft leavened bread from the tandoor.',     35, '🫓', true, true, 0, '{}', 6),
('butter-naan',        'roti', 'Butter Naan',        'Soft fluffy naan brushed with butter.',     40, '🫓', true, true, 0, '{bestseller}', 7),
('cheese-garlic-naan', 'roti', 'Cheese Garlic Naan', 'Naan topped with garlic and melted cheese.',70, '🫓', true, true, 0, '{bestseller}', 8),
('masala-kulcha',      'roti', 'Masala Kulcha',      'Leavened bread stuffed with spiced masala.',60, '🫓', true, true, 1, '{}', 9),
('pudina-kulcha',      'roti', 'Pudina Kulcha',      'Mint-flavoured kulcha.',                    60, '🫓', true, true, 0, '{}', 10),
('onion-kulcha',       'roti', 'Onion Kulcha',       'Kulcha stuffed with caramelised onions.',   60, '🫓', true, true, 1, '{}', 11),

-- MAIN COURSE VEG
('steamed-rice',          'main-veg', 'Steamed Rice',           'Plain steamed basmati rice.',                        80,  '🍚', true, true, 0, '{}', 1),
('jeera-rice',            'main-veg', 'Jeera Rice',             'Basmati rice tempered with cumin.',                  100, '🍚', true, true, 0, '{}', 2),
('onion-tomato-rice',     'main-veg', 'Onion Tomato Rice',      'Spiced rice with onion and tomato.',                 120, '🍚', true, true, 1, '{}', 3),
('masala-rice',           'main-veg', 'Masala Rice',            'Flavourful spiced rice.',                            130, '🍚', true, true, 1, '{}', 4),
('veg-pulao',             'main-veg', 'Veg Pulao',              'Aromatic basmati rice with vegetables.',             130, '🍚', true, true, 1, '{}', 5),
('veg-biryani',           'main-veg', 'Veg Biryani',            'Fragrant dum-cooked rice with vegetables.',          160, '🍚', true, true, 2, '{}', 6),
('dal-khichdi',           'main-veg', 'Dal Khichdi',            'Comforting rice and lentil dish.',                   150, '🥣', true, true, 0, '{}', 7),
('masala-khichdi',        'main-veg', 'Masala Khichdi',         'Spiced dal and rice khichdi.',                       160, '🥣', true, true, 1, '{}', 8),
('dal-plain',             'main-veg', 'Dal Plain',              'Simple boiled yellow dal.',                          80,  '🥘', true, true, 0, '{}', 9),
('dal-fry',               'main-veg', 'Dal Fry',                'Yellow lentils with ghee tempering.',                120, '🥘', true, true, 1, '{bestseller}', 10),
('dal-tadka',             'main-veg', 'Dal Tadka',              'Lentils with a bold aromatic tadka.',                130, '🥘', true, true, 1, '{bestseller}', 11),
('dal-do-pyaza',          'main-veg', 'Dal Do Pyaza',           'Dal cooked with double onions.',                     140, '🥘', true, true, 1, '{}', 12),
('jeera-dal',             'main-veg', 'Jeera Dal',              'Lentils tempered with cumin.',                       110, '🥘', true, true, 0, '{}', 13),
('dal-makhani',           'main-veg', 'Dal Makhani',            'Slow-cooked black lentils in buttery gravy.',        180, '🥘', true, true, 1, '{bestseller}', 14),
('paneer-masala',         'main-veg', 'Paneer Masala',          'Paneer in a flavourful masala gravy.',               180, '🍛', true, true, 2, '{}', 15),
('paneer-butter-masala',  'main-veg', 'Paneer Butter Masala',   'Cottage cheese in rich creamy tomato gravy.',        230, '🍛', true, true, 1, '{bestseller}', 16),
('paneer-do-pyaza',       'main-veg', 'Paneer Do Pyaza',        'Paneer with double onions.',                         230, '🍛', true, true, 2, '{}', 17),
('paneer-sahuji',         'main-veg', 'Paneer Sahuji',          'Chhattisgarh-style paneer preparation.',             230, '🍛', true, true, 2, '{local}', 18),
('paneer-kadhai-tadka',   'main-veg', 'Paneer Kadhai Tadka',    'Paneer cooked kadhai-style.',                        240, '🍛', true, true, 2, '{}', 19),
('paneer-punjabi-masala', 'main-veg', 'Paneer Punjabi Masala',  'Rich Punjabi-style paneer.',                         250, '🍛', true, true, 2, '{}', 20),
('paneer-lababdar',       'main-veg', 'Paneer Lababdar Masala', 'Paneer in velvety indulgent gravy.',                 250, '🍛', true, true, 1, '{chef-special}', 21),
('paneer-lachhedar',      'main-veg', 'Paneer Lachhedar Masala','Paneer with layered spiced gravy.',                  260, '🍛', true, true, 2, '{}', 22),
('paneer-tikka-masala',   'main-veg', 'Paneer Tikka Masala',    'Grilled paneer in smoky masala gravy.',              280, '🍛', true, true, 2, '{}', 23),
('paneer-kofta-masala',   'main-veg', 'Paneer Kofta Masala',    'Paneer kofta balls in rich gravy.',                  280, '🍛', true, true, 1, '{}', 24),
('palak-paneer',          'main-veg', 'Palak Paneer',           'Paneer in creamy spinach gravy.',                    190, '🍛', true, true, 1, '{bestseller}', 25),
('paneer-bhurji',         'main-veg', 'Paneer Bhurji',          'Scrambled paneer with onion and tomato.',            200, '🍳', true, true, 2, '{}', 26),
('kaju-masala',           'main-veg', 'Kaju Masala',            'Cashews in rich creamy masala gravy.',               300, '🍛', true, true, 1, '{chef-special}', 27),
('soya-chaap-masala',     'main-veg', 'Soya Chaap Masala',      'Soya chaap in spiced masala gravy.',                 260, '🍢', true, true, 2, '{}', 28),
('mushroom-masala',       'main-veg', 'Mushroom Masala',        'Mushrooms in spiced tomato masala.',                 260, '🍄', true, true, 2, '{}', 29),
('mushroom-kadhai',       'main-veg', 'Mushroom Kadhai',        'Mushrooms cooked kadhai-style.',                     260, '🍄', true, true, 2, '{}', 30),
('veg-kadhai',            'main-veg', 'Veg Kadhai',             'Mixed vegetables kadhai-style.',                     260, '🍛', true, true, 2, '{}', 31),
('mix-veg',               'main-veg', 'Mix Veg',                'Seasonal vegetables in spiced gravy.',               170, '🥦', true, true, 1, '{}', 32),
('veg-keema',             'main-veg', 'Veg Keema',              'Finely minced vegetable keema.',                     170, '🍛', true, true, 2, '{}', 33),
('veg-khasta',            'main-veg', 'Veg Khasta',             'Crispy fried vegetables in light gravy.',            170, '🥦', true, true, 1, '{}', 34),
('veg-jaipuri',           'main-veg', 'Veg Jaipuri',            'Rajasthani-style vegetable curry.',                  160, '🍛', true, true, 2, '{}', 35),
('aloo-gobhi-matar',      'main-veg', 'Aloo Gobhi Matar',       'Potato, cauliflower and peas dry masala.',           180, '🥔', true, true, 1, '{}', 36),
('gobhi-masala',          'main-veg', 'Gobhi Masala',           'Cauliflower in spiced masala.',                      150, '🥦', true, true, 1, '{}', 37),
('aloo-dum-punjabi',      'main-veg', 'Aloo Dum Punjabi',       'Baby potatoes slow-cooked Punjabi style.',           180, '🥔', true, true, 2, '{}', 38),
('aloo-dum-chingari',     'main-veg', 'Aloo Dum Chingari',      'Baby potatoes in fiery Chingari masala.',            170, '🥔', true, true, 3, '{local}', 39),
('bhindi-masala',         'main-veg', 'Bhindi Masala',          'Okra stir-fried with spices.',                       190, '🍽️', true, true, 1, '{}', 40),
('bhindi-kurkure',        'main-veg', 'Bhindi Kurkure',         'Crispy fried okra.',                                 180, '🍽️', true, true, 1, '{}', 41),
('veg-kolhapuri',         'main-veg', 'Veg Kolhapuri',          'Fiery Kolhapuri-style vegetable curry.',             180, '🍛', true, true, 3, '{}', 42),
('papad-churi',           'main-veg', 'Papad Churi',            'Crushed papad in spiced masala.',                    180, '🍽️', true, true, 2, '{}', 43),

-- MAIN COURSE NON-VEG
('chicken-masala',          'main-nonveg', 'Chicken Masala (4 pc)',          'Chicken in rich spiced masala gravy.',          300, '🍲', false, true, 2, '{bestseller}', 1),
('chicken-butter-masala',   'main-nonveg', 'Chicken Butter Masala (4 pc)',   'Tender chicken in velvety buttery gravy.',      350, '🍲', false, true, 1, '{bestseller}', 2),
('chicken-tikka-masala-m',  'main-nonveg', 'Chicken Tikka Masala (4 pc)',    'Grilled chicken in smoky masala gravy.',        300, '🍲', false, true, 2, '{}', 3),
('chicken-kadhai',          'main-nonveg', 'Chicken Kadhai (4 pc)',          'Chicken with peppers and ground spices.',       300, '🍲', false, true, 2, '{}', 4),
('chicken-curry',           'main-nonveg', 'Chicken Curry (4 pc)',           'Classic home-style chicken curry.',             280, '🍲', false, true, 2, '{}', 5),
('chicken-rara',            'main-nonveg', 'Chicken Rara (4 pc)',            'Chicken cooked with minced chicken.',           350, '🍲', false, true, 3, '{}', 6),
('chicken-punjabi',         'main-nonveg', 'Chicken Punjabi (4 pc)',         'Punjabi-style hearty chicken.',                 320, '🍲', false, true, 2, '{}', 7),
('chicken-kolhapuri',       'main-nonveg', 'Chicken Kolhapuri (4 pc)',       'Fiery Kolhapuri chicken curry.',                280, '🍲', false, true, 3, '{}', 8),
('chicken-bhuna',           'main-nonveg', 'Chicken Bhuna (4 pc)',           'Slow-roasted chicken in dry masala.',           300, '🍲', false, true, 2, '{}', 9),
('chicken-dehati',          'main-nonveg', 'Chicken Dehati (4 pc)',          'Rustic village-style chicken.',                 250, '🍲', false, true, 2, '{}', 10),
('chicken-tandoori-masala', 'main-nonveg', 'Chicken Tandoori Masala (4 pc)', 'Tandoor-finished chicken in masala.',          320, '🍲', false, true, 2, '{}', 11),

-- BIRYANI SPECIAL
('chicken-dum-biryani',        'biryani', 'Chicken Dum Biryani (Full)',        'Basmati and chicken slow-cooked on dum.',       220, '🍛', false, true, 2, '{bestseller}', 1),
('chicken-hyderabadi-biryani', 'biryani', 'Chicken Hyderabadi Biryani (Full)', 'Aromatic Hyderabadi dum biryani.',              230, '🍛', false, true, 2, '{bestseller}', 2),
('chicken-roast-biryani',      'biryani', 'Chicken Roast Biryani (Full)',      'Biryani with tandoor-roasted chicken.',         250, '🍛', false, true, 2, '{}', 3),
('chicken-tandoori-biryani',   'biryani', 'Chicken Tandoori Biryani (Full)',   'Biryani with smoky tandoori chicken.',          250, '🍛', false, true, 2, '{}', 4),
('egg-biryani',                'biryani', 'Egg Biryani (Full)',                'Fragrant rice with spiced boiled eggs.',        180, '🍚', false, true, 2, '{}', 5),
('fish-biryani',               'biryani', 'Fish Biryani (Full)',               'Fragrant dum biryani with tender fish.',        200, '🍚', false, true, 2, '{}', 6),
('mutton-biryani',             'biryani', 'Mutton Biryani (Full)',             'Rich slow-cooked mutton biryani.',              350, '🍛', false, true, 2, '{chef-special}', 7),
('veg-biryani-b',              'biryani', 'Veg Biryani',                       'Fragrant dum-cooked rice with vegetables.',     160, '🍚', true,  true, 2, '{}', 8),

-- MUTTON SPECIAL
('mutton-curry',      'mutton', 'Mutton Curry (4 pc)',      'Classic mutton curry with whole spices.',    360, '🥩', false, true, 2, '{bestseller}', 1),
('mutton-masala',     'mutton', 'Mutton Masala (4 pc)',     'Mutton in bold masala.',                     380, '🥩', false, true, 2, '{}', 2),
('mutton-rogan-josh', 'mutton', 'Mutton Rogan Josh (4 pc)', 'Kashmiri-style mutton in aromatic gravy.',  410, '🥩', false, true, 2, '{chef-special}', 3),

-- FISH SPECIAL
('fish-fry',    'fish', 'Fish Fry (4 pc)',    'Crispy golden fried fish fillets.',       230, '🐟', false, true, 2, '{bestseller}', 1),
('fish-roast',  'fish', 'Fish Roast (4 pc)',  'Tandoor-roasted fish.',                   240, '🐟', false, true, 2, '{}', 2),
('fish-curry',  'fish', 'Fish Curry (4 pc)',  'Traditional fish curry.',                 260, '🐟', false, true, 2, '{}', 3),
('fish-masala', 'fish', 'Fish Masala (4 pc)', 'Fish in bold masala gravy.',              280, '🐟', false, true, 2, '{}', 4),
('fish-lapeta', 'fish', 'Fish Lapeta',        'Chhattisgarhi-style spicy fish.',         300, '🐟', false, true, 3, '{local,chef-special}', 5),

-- BEVERAGES
('fresh-lime-soda',       'beverages', 'Fresh Lime Soda',           'Sweet-and-salty fresh lime soda.',              40,  '🥤', true, true, 0, '{}', 1),
('fresh-lime-water',      'beverages', 'Fresh Lime Water',          'Refreshing fresh lime with water.',             50,  '🍋', true, true, 0, '{}', 2),
('butter-milk',           'beverages', 'Butter Milk',               'Chilled spiced buttermilk.',                    50,  '🥛', true, true, 0, '{}', 3),
('lassi',                 'beverages', 'Lassi',                     'Thick chilled sweet yogurt drink.',             50,  '🥛', true, true, 0, '{}', 4),
('green-mojito',          'beverages', 'Green Mojito',              'Minty fresh mocktail.',                         80,  '🍹', true, true, 0, '{}', 5),
('blue-lagoon',           'beverages', 'Blue Lagoon',               'Refreshing blue mocktail.',                     80,  '🍹', true, true, 0, '{}', 6),
('orange-shake',          'beverages', 'Orange Shake',              'Fresh orange milkshake.',                       80,  '🍊', true, true, 0, '{}', 7),
('pineapple-shake',       'beverages', 'Pineapple Shake',           'Tropical pineapple milkshake.',                 80,  '🍍', true, true, 0, '{}', 8),
('cold-coffee',           'beverages', 'Cold Coffee',               'Chilled blended coffee.',                       80,  '☕', true, true, 0, '{}', 9),
('mango-shake',           'beverages', 'Mango Shake',               'Creamy mango milkshake.',                       110, '🥭', true, true, 0, '{}', 10),
('strawberry-shake',      'beverages', 'Strawberry Shake',          'Fresh strawberry milkshake.',                   110, '🍓', true, true, 0, '{}', 11),
('chocolate-shake',       'beverages', 'Chocolate Shake',           'Rich chocolate milkshake.',                     110, '🍫', true, true, 0, '{}', 12),
('oreo-shake',            'beverages', 'Oreo Shake',                'Creamy Oreo milkshake.',                        110, '🍪', true, true, 0, '{}', 13),
('kitkat-shake',          'beverages', 'KitKat Shake',              'KitKat blended milkshake.',                     110, '🍫', true, true, 0, '{}', 14),
('dry-fruit-shake',       'beverages', 'Dry Fruit Shake',           'Milkshake with assorted dry fruits.',           110, '🥛', true, true, 0, '{}', 15),
('fruit-punch',           'beverages', 'Fruit Punch',               'Mixed fruit punch mocktail.',                   110, '🍹', true, true, 0, '{}', 16),
('cold-coffee-ice-cream', 'beverages', 'Cold Coffee with Ice Cream','Cold coffee topped with ice cream.',            110, '🍦', true, true, 0, '{}', 17),

-- TEA & COFFEE
('regular-tea',       'tea-coffee', 'Regular Tea',       'Classic milk tea.',                         15, '🍵', true, true, 0, '{}', 1),
('masala-tea',        'tea-coffee', 'Masala Tea',        'Spiced milk tea with whole spices.',        20, '🍵', true, true, 0, '{bestseller}', 2),
('adrak-elaichi-tea', 'tea-coffee', 'Adrak Elaichi Tea', 'Ginger and cardamom tea.',                  20, '🍵', true, true, 0, '{}', 3),
('black-lemon-tea',   'tea-coffee', 'Black Lemon Tea',   'Light black tea with lemon.',               20, '🍵', true, true, 0, '{}', 4),
('jaggery-tea',       'tea-coffee', 'Jaggery Tea',       'Naturally sweetened tea with jaggery.',     20, '🍵', true, true, 0, '{}', 5),
('coffee',            'tea-coffee', 'Coffee',            'Hot brewed coffee.',                        20, '☕', true, true, 0, '{}', 6),

-- SWEETS & SALADS
('gulab-jamun',     'sweets-salads', 'Gulab Jamun (2 pc)', 'Warm milk dumplings in rose-cardamom syrup.', 30,  '🍩', true, true, 0, '{bestseller}', 1),
('rabdi-jalebi',    'sweets-salads', 'Rabdi Jalebi',       'Crispy jalebi with thick rabdi.',             100, '🍮', true, true, 0, '{chef-special}', 2),
('papad-dry',       'sweets-salads', 'Papad Dry',          'Plain roasted papad.',                        10,  '🍽️', true, true, 0, '{}', 3),
('papad-fry',       'sweets-salads', 'Papad Fry',          'Deep-fried crispy papad.',                    15,  '🍽️', true, true, 0, '{}', 4),
('papad-masala',    'sweets-salads', 'Papad Masala',       'Roasted papad with spiced masala.',           30,  '🍽️', true, true, 2, '{}', 5),
('onion-salad',     'sweets-salads', 'Onion Salad',        'Fresh onion salad with lemon.',               30,  '🥗', true, true, 1, '{}', 6),
('green-salad',     'sweets-salads', 'Green Salad',        'Fresh garden salad.',                         60,  '🥗', true, true, 0, '{}', 7),
('kachumber-salad', 'sweets-salads', 'Kachumber Salad',    'Cucumber, tomato and onion salad.',           40,  '🥗', true, true, 0, '{}', 8),
('peanut-salad',    'sweets-salads', 'Peanut Salad',       'Spiced peanut salad.',                        80,  '🥜', true, true, 1, '{}', 9),
('boondi-raita',    'sweets-salads', 'Boondi Raita',       'Chilled yogurt with boondi.',                 80,  '🥛', true, true, 0, '{}', 10),
('veg-raita',       'sweets-salads', 'Veg Raita',          'Chilled yogurt with fresh vegetables.',       70,  '🥛', true, true, 0, '{}', 11);
